# Schema for the configuration files of the ip2country module.

ip2country.settings:
  type: config_object
  mapping:
    watchdog:
      type: boolean
      label: 'Log database updates to watchdog'
    rir:
      type: string
      label: 'RIR to use for database updates'
    md5_checksum:
      type: boolean
      label: 'Calculate and compare MD5 checksum for database updates'
    update_interval:
      type: integer
      label: 'Database update interval in seconds'

    debug:
      type: boolean
      label: 'Operate in debug mode'
    test_type:
      type: integer
      label: 'Select country spoofing or IP address spoofing'
    test_country:
      type: string
      label: 'Country to spoof'
    test_ip_address:
      type: string
      label: 'IP address to spoof'
